### PR TITLE
Fixed fixtures/next/results and created women's equivalents with wfixtures/wnext/wresults.  

### PR DESCRIPTION
**Pull request by ingenium21**

### CODE REVIEW

**Comment by ingenium21** [comment]
Some examples 
image
image
image
image
image
image

**Comment by ingenium21** [comment]
resolves #101 , resolves #104

**Comment by reddit-tennis** [comment]
Think I've given you feedback in Discord in regards to the functionality, haven't gone through the logic quite yet but general comment on the code style that might be useful for you.

Please can you use lowercase variables and underscores if you need to separate words. Camelcase is out of place in Python.

 
More details here https://peps.python.org/pep-0008/#prescriptive-naming-conventions

**Review by AndyReifman — APPROVED** [review]
Looks good. Agree that we need to get some consistent formatting in this project at some point.

**Review by ash663 — APPROVED** [review]
approving based on “Trust me bro”

**Pull request merged**
